management:
  endpoints:
    web:
      exposure:
        include:
        - "*"

  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true
info:
  author: vasudeep
  version: 2.0
